import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_URL = 'https://genezio.com';
const OUTPUT_FILE = path.join(__dirname, '../public/sitemap.xml');

// Static routes
const staticRoutes = [
    '/',
    '/pricing',
    '/conversational-brand-presence',
    '/increase-conversion',
    '/increase-csat',
    '/glossary',
    '/terms-and-conditions',
    '/support-terms',
    '/data-processing-agreement',
    '/privacy-policy',
    '/policy'
];

function extractGlossarySlugs() {
    const glossaryPath = path.join(__dirname, '../src/polymet/pages/glossary.tsx');
    const content = fs.readFileSync(glossaryPath, 'utf-8');

    const termRegex = /term:\s*"([^"]+)"/g;
    const slugs = [];
    let match;

    while ((match = termRegex.exec(content)) !== null) {
        const term = match[1];
        const slug = term
            .toLowerCase()
            .replace(/\s+/g, "-")
            .replace(/[^a-z0-9-]/g, "");
        slugs.push(`/glossary/${slug}`);
    }

    return slugs;
}

function extractBlogSlugs() {
    const blogPath = path.join(__dirname, '../src/polymet/pages/blog-post.tsx');
    const content = fs.readFileSync(blogPath, 'utf-8');

    const slugRegex = /"([^"]+)":\s*{/g;
    const slugs = [];
    let match;

    while ((match = slugRegex.exec(content)) !== null) {
        if (!match[1].includes(' ')) {
            slugs.push(`/blog/${match[1]}`);
        }
    }

    return slugs;
}

function generateSitemap() {
    console.log('Generating sitemap...');

    const glossarySlugs = extractGlossarySlugs();
    console.log(`Found ${glossarySlugs.length} glossary terms.`);

    const blogSlugs = extractBlogSlugs();
    console.log(`Found ${blogSlugs.length} blog posts.`);

    const allRoutes = [
        ...staticRoutes,
        ...glossarySlugs,
        ...blogSlugs
    ];

    // Get current date in YYYY-MM-DD format
    const today = new Date().toISOString().split('T')[0];

    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<!--
Generated by scripts/generate-sitemap.js
-->
${allRoutes.map(route => `<url>
      <loc>${BASE_URL}${route}</loc>
      <lastmod>${today}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>1</priority>
</url>`).join('\n')}
</urlset>`;

    fs.writeFileSync(OUTPUT_FILE, sitemap);
    console.log(`Sitemap generated at ${OUTPUT_FILE}`);
}

generateSitemap();
