baseURL = "/"  
languageCode = "en-us"  
title = "DeployApps"  
theme = "genezio-theme"  
enableRobotsTXT = true
paginate = 9

[params]
    primary_color = "#6f42c1"

[params.footer]
        description = "DeployApps is a new paradigm in cloud native programming, making it accessible to everyone, allowing elegant and quick development of websites, mobile apps, IoT apps, and many others."
        
[permalinks]
    posts = "/blog/:title/"
    author = "/author/:slug/"

[outputFormats.imagessitemap]
  baseName  = 'imagessitemap'
  mediaType = 'application/xml'
  noUgly = true # default is false

[outputs]
  page = [ "html"]
  home = [ "html", "rss", "imagessitemap"]
