baseURL = "/"  
languageCode = "en-us"  
title = "Genezio"  
theme = "genezio-theme"  
enableRobotsTXT = true
paginate = 9

[params]
    primary_color = "#6f42c1"

[params.footer]
        description = "Genezio’s blog: Your expert resource on AI agent evaluation, continuous testing, and prompt injection security. Master chatbot optimization and build a secure CX."
        
[permalinks]
    posts = "/blog/:title/"
    author = "/author/:slug/"

[outputFormats.imagessitemap]
  baseName  = 'imagessitemap'
  mediaType = 'application/xml'
  noUgly = true # default is false

[outputs]
  page = [ "html"]
  home = [ "html", "rss", "imagessitemap"]
